server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 1234

